name: countersapp_bloccubit_playground
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  async: ^2.12.0
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  bloc_test: ^10.0.0
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  internet_connection_checker: ^3.0.1
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
